### ISSUE TITLE
Functions Not Defined

### ISSUE THREAD

**Issue by l-zeuch** [jo3-l/action-check-yag-tmpl-syntax#3]
**Description:**
The newly (been a while to be honest) added templates are considered not defined, hence failing the workflow run suite.

**Steps to reproduce:**
Configuration stub:
```yaml
- uses: jo3-l/action-check-yag-tmpl-syntax@v2
  with:
    include: '**/*.gotmpl'
```
Template stub:
```go
{{ dbDelMultiple (sdict "userID" .User.ID "pattern" "test%") 100 0 }}
{{ dbRank (sdict "userID" .User.ID) .User.ID "test" }}
```
See error:
```
function "dbDelMultiple" not defined
function "dbRank" not defined
```
----
There's probably more templates not defined (yet), but these were the ones that I caught.
