### ISSUE TITLE
Recurring: Functions Not Defined

### ISSUE THREAD

**Issue by l-zeuch** [jo3-l/action-check-yag-tmpl-syntax#4]
**Description:**
The newly template functions are not yet known to this workflow, hence failing the run suite.

**Steps to reproduce:**
Config stub:
```yml
- uses: jo3-l/action-check-yag-tmpl-syntax@v2.0.1
  with:
    include: '**/*.gotmpl'
```

Then, just use some new template function that is not yet known to this workflow.

---
This issue is recurring, as YAGPDB relatively constantly adds new template functions, so it may be appropriate to implement some sort of auto-scanning.

Also, as far as I know, using `@v2` should always use the latest v2, no matter the minor or patch level, but don't quote me on that.
